version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo_lunar_sniffer_DB
    ports:
      - "27017:27017"
    volumes:
      - /media/mglos/HDD_8TB/MONGO/DB:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

  redis:
    image: redis:7.0
    container_name: redis_lunar_sniffer
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /media/mglos/HDD_8TB/REDIS:/data
    restart: always